name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0' # Runs once every week
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "hungtrinh2001"
          git config user.email "killdate123456@gmail.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/recloudstream/cloudstream.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master --ff-only || echo "No changes to merge"

      - name: Push changes to fork
        run: git push origin master
